---
title: "Mini Project 3"
author: "Leigh Tanji and Samantha Bryce"
date: "2017年11???15日"
output: html_document
---

```{r}
library(mdsr)
library(RMySQL)
library(dplyr)
library(ggplot2)
```


Inner joining title and movie kind, Sequels.
```{r}
imdb_sequels <- dbConnect_scidb(dbname = "imdb")
class(imdb_sequels)

imdb_sequels <- imdb_sequels %>%
  dbGetQuery("SELECT DISTINCT title.id, movie_id, title, kind_id, production_year, link_type_id
FROM imdb.title
JOIN movie_link
ON title.id = movie_link.movie_id
WHERE (kind_id = '1') 
AND (link_type_id = '1' OR link_type_id = '2')
;")

```

Cleaning up the data via dplyr. Got rid of duplicate rows, movie ids, kind ids, etc. Arranged number of sequels per year.
```{r}
imdb_sequels_no <- imdb_sequels %>%
  group_by(production_year) %>%
  distinct(movie_id, .keep_all = TRUE) %>%
  summarise(n_sequels = n()) %>%
  select(production_year, n_sequels) %>%
  arrange(production_year)

imdb_sequels_no

list2env(imdb_sequels_no, envir = .GlobalEnv)
```


#Finding Remakes
Going into SQL to sort out remakes by kind id. 
```{r}
imdb_remakes <- dbConnect_scidb(dbname = "imdb")
class(imdb_remakes)

imdb_remakes <- imdb_remakes %>%
  dbGetQuery("SELECT DISTINCT title.id, movie_id, title, kind_id, production_year, link_type_id
FROM imdb.title
JOIN movie_link
ON title.id = movie_link.movie_id
WHERE kind_id = 1
AND (link_type_id = 3 OR link_type_id = 4);")
```

Sorting out number of remakes per year. 
```{r}
imdb_remakes_no <- imdb_remakes%>%
  group_by(production_year) %>%
  distinct(movie_id, .keep_all = TRUE) %>%
  summarise(n_remakes = n()) %>%
  select(production_year, n_remakes) %>%
  arrange(production_year)

imdb_remakes_no

list2env(imdb_remakes_no, envir = .GlobalEnv)
```

#Finding Reboots
Going into SQL to sort out reboots by kind id.
```{r}
imdb_reboots <- dbConnect_scidb(dbname = "imdb")
class(imdb_reboots)

imdb_reboots <- imdb_reboots %>%
  dbGetQuery("SELECT DISTINCT title.id, movie_id, title, kind_id, production_year, link_type_id
FROM imdb.title
JOIN movie_link
ON title.id = movie_link.movie_id
WHERE (kind_id = '1') 
AND (link_type_id = '13' OR link_type_id = '11' OR link_type_id = '12');")
 
```

Making a dataframe of reboots per year. 
```{r}
imdb_reboots_no <- imdb_reboots %>%
  group_by(production_year) %>%
  distinct(movie_id, .keep_all = TRUE) %>%
  summarise(n_reboots = n()) %>%
  select(production_year, n_reboots) %>%
  arrange(production_year)

imdb_reboots_no
list2env(imdb_reboots_no, envir = .GlobalEnv)
```































